name: master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "master"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 17.0.5
      uses: actions/setup-java@v1
      with:
        java-version: 17.0.5
    - name: Run checks
      run: ./gradlew clean check
